[jjo] enable pubsub integration tests
* integration-tests.bats: enable `pubsub`

* harden `kafka-0` readiness checks to (more) deterministically run
  `make -C examples pubsub pubsub-verify`
  - add livenessProbe to kafka-0:
    added tcp port 9092 probing, specially needed when testing (i.e. full
    minikube/dind cluster being brought up), kafka startup have been
    observed to fail from e.g. `zookeeper.kubeless` failed resolution
    (kube-dns may have not completely settled), and its containers'
    `/run.sh` does a single shot run w/o retry
  - enhance related functions:
    _wait_for_kubeless_kafka_{server,topic}_ready
  - tail the whole log, to avoid races

* misc:
  - add TRAVIS_DUMP_LOGS for force log dumping even if successful
  - only delete func if not present

diff --git a/script/integration-tests b/script/integration-tests
--- a/script/integration-tests
+++ b/script/integration-tests
@@ -61,7 +61,7 @@ exit_code=$?
 # Just showing remaining k8s objects
 kubectl get all --all-namespaces
 
-[[ ${exit_code} == 0 ]] || {
+if [ ${exit_code} -ne 0 -o -n "${TRAVIS_DUMP_LOGS}" ]; then
     echo "INFO: Build ERRORed, dumping logs: ##"
     for ns in kubeless default; do
         echo "### LOGs: namespace: ${ns} ###"
@@ -69,6 +69,8 @@ kubectl get all --all-namespaces
     done
     echo "INFO: LOGs: pod: kube-dns ###"
     kubectl logs -n kube-system -l k8s-app=kube-dns -c kubedns
-}
+    echo "INFO: LOGs: END"
+fi
+[ ${exit_code} -eq 0 ] && echo "INFO: $0: SUCCESS" || echo "ERROR: $0: FAILED"
 exit ${exit_code}
 # vim: sw=4 ts=4 et si
